### ISSUE TITLE
Check this resource

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/getting-started-with-sonic-pi#1]
Hi @samaaron, at Pam's request and in preparation for both Sonic Pi Live summer schools and the "toolkit" needed for the project I've created this getting started with Sonic Pi 2 resource. I've based it on my old resource and some of your code. Can you take a look and add/remove anything you think is necessary. I was thinking of adding another worksheet for effects and then parameters.  Thoughts?

**Comment by bennuttall** [comment]
Can this issue be closed?

**Comment by samaaron** [comment]
Not sure what's actionable from my perspective any more. I' pretty sure I've since updated and worked through it...

**Comment by MissPhilbin** [comment]
I'm sure we can just open a new issue if there are any problems :)
