### ISSUE TITLE
feedback from projects site

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/getting-started-with-sonic-pi#18]
URL: /en/projects/getting-started-with-sonic-pi

Hey, I just went through all of your instructions - preparing for a class next week - and your Live code! section seems to be incorrect. Using a regular loop and pressing play again appears to just run both the old and the new at the same time, and you have no reference to the live_loop function seen in the example youtube videos and other instructions.
Otherwise, this was GREAT, I'm gonna use it for my class - with my own changes to the live coding bit, of course.

**Comment by lawsie** [comment]
It's true that this isn't a live loop. However, following the instructions does produce what it says it produces. I suspect the person did not comment out the loop as instructed. The resource needs updating though to include live loop.
